import React, {useState} from 'react';

export function AIFilmmakingPanel({visible, apiFetch, story, characters, scenes, research, rootsFoundation, era, storyType, profile, setScenes, setMessage}){
  const [tab,setTab]=useState('plan'); const [data,setData]=useState(null); const [busy,setBusy]=useState(false); const [status,setStatus]=useState('');
  if(!visible)return null;
  async function run(path,payload){setBusy(true);setStatus('Analyzing production…');try{const r=await apiFetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||'AI analysis failed.');setData(d);setStatus('Analysis ready.');return d;}catch(e){setStatus(e.message||'AI analysis failed.')}finally{setBusy(false)}}
  async function plan(){await run('/api/ai/film-plan',{story,characters,research,rootsFoundation,era,storyType,profile});}
  async function checkContinuity(){await run('/api/ai/continuity',{characters,scenes});}
  async function auditResearch(){await run('/api/ai/research-audit',{research,era,storyType});}
  function applyPlan(){if(!data?.beats)return;setScenes(data.beats.map(b=>({id:`ai-scene-${Date.now()}-${b.number}`,number:b.number,title:b.title,prompt:b.logline,camera:b.camera,status:'draft',primaryCharacterId:characters[0]?.id||'',aiBeat:b.beat,aiVisualGoal:b.visualGoal})));setMessage?.(`AI production plan applied: ${data.beats.length} scenes.`);setStatus('Scene plan applied to storyboard.');}
  return <section className="card-inset ai-copilot"><div className="eyebrow">AI FILMMAKING INTELLIGENCE</div><h3>Director Copilot</h3><p className="muted">Turn your story into a production plan, continuity check and research readiness review before spending generation credits.</p><div className="panel-tabs"><button className={tab==='plan'?'active':''} onClick={()=>setTab('plan')}>Story intelligence</button><button className={tab==='continuity'?'active':''} onClick={()=>setTab('continuity')}>Continuity</button><button className={tab==='research'?'active':''} onClick={()=>setTab('research')}>Research guard</button></div>
    {tab==='plan'&&<><button className="generate" onClick={plan} disabled={busy}>{busy?'Analyzing…':'Analyze & build director plan'}</button>{data?.beats&&<><div className="ai-score"><strong>{data.readiness.score}%</strong><span>production readiness</span></div><div className="ai-beats">{data.beats.map(b=><div key={b.number} className="ai-beat"><b>{b.number}. {b.title}</b><small>{b.camera} · {b.shotSize} · {b.lighting}</small><small>{b.sound} · {b.transition}</small><p>{b.logline}</p></div>)}</div><div className="inline-actions"><button onClick={applyPlan}>Apply scene plan</button></div>{data.readiness.missing?.length>0&&<div className="ai-warning"><b>Before rendering</b>{data.readiness.missing.map((x,i)=><div key={i}>• {x}</div>)}</div>}</>}</>}
    {tab==='continuity'&&<><button className="generate" onClick={checkContinuity} disabled={busy}>{busy?'Checking…':'Run continuity check'}</button>{data?.checks&&<div className="passport-grid"><div><small>Characters</small><strong>{data.checks.characters}</strong></div><div><small>Scenes</small><strong>{data.checks.scenes}</strong></div><div><small>Assigned</small><strong>{data.checks.assignedScenes}</strong></div><div><small>Ready</small><strong>{data.checks.readyScenes}</strong></div></div>}{data?.warnings?.map((x,i)=><div className="ai-warning" key={i}>• {x}</div>)}{data?.ok&&<div className="ai-success">Continuity checks passed.</div>}</>}
    {tab==='research'&&<><button className="generate" onClick={auditResearch} disabled={busy}>{busy?'Auditing…':'Audit research readiness'}</button>{data&&<><div className={data.ready?'ai-success':'ai-warning'}>{data.ready?'Research fields are complete.':'Research still has gaps.'}</div>{data.missing?.map((x,i)=><div key={i}>• Missing: {x}</div>)}{data.cautions?.map((x,i)=><div key={i} className="ai-warning">• {x}</div>)}</>}</>}
    {status&&<div className="status">{status}</div>}</section>
}
