import React,{useEffect,useMemo,useState} from 'react';

export function ProductionPanel({visible,apiFetch,projectId,scenes=[]}){
 const [tab,setTab]=useState('review'),[versions,setVersions]=useState([]),[comments,setComments]=useState([]),[approvals,setApprovals]=useState([]),[passport,setPassport]=useState(null),[comment,setComment]=useState(''),[sceneId,setSceneId]=useState(''),[status,setStatus]=useState('');
 async function get(path){const r=await apiFetch(path);const d=await r.json();if(!r.ok)throw new Error(d.message||'Request failed.');return d}
 async function refresh(){if(!projectId)return;try{const [v,c,a,p]=await Promise.all([get(`/api/projects/${projectId}/versions`),get(`/api/projects/${projectId}/comments`),get(`/api/projects/${projectId}/approvals`),get(`/api/projects/${projectId}/passport`)]);setVersions(v.versions||[]);setComments(c.comments||[]);setApprovals(a.approvals||[]);setPassport(p.passport||null)}catch(e){setStatus(e.message)}}
 useEffect(()=>{if(visible)refresh()},[visible,projectId]);
 async function saveVersion(){try{const r=await apiFetch(`/api/projects/${projectId}/versions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:`Studio snapshot ${new Date().toLocaleString()}`})});const d=await r.json();if(!r.ok)throw new Error(d.message);setVersions(v=>[d.version,...v]);setStatus('Production snapshot saved.')}catch(e){setStatus(e.message)}}
 async function addComment(){if(!comment.trim())return;try{const r=await apiFetch(`/api/projects/${projectId}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:comment,sceneId:sceneId||null})});const d=await r.json();if(!r.ok)throw new Error(d.message);setComments(c=>[...c,d.comment]);setComment('');setStatus('Review note added.')}catch(e){setStatus(e.message)}}
 async function approve(id,next){try{const r=await apiFetch(`/api/projects/${projectId}/scenes/${encodeURIComponent(id)}/approval`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next})});const d=await r.json();if(!r.ok)throw new Error(d.message);setApprovals(a=>[d.approval,...a.filter(x=>x.scene_id!==id)]);setStatus(`Scene ${id} marked ${next}.`)}catch(e){setStatus(e.message)}}
 const approvalSummary=useMemo(()=>{const map=new Map(approvals.map(a=>[String(a.scene_id),a.status]));const approved=scenes.filter(s=>['approved','locked'].includes(map.get(String(s.id)))).length;const pending=scenes.length-approved;return {approved,pending,total:scenes.length,ready:scenes.length>0&&pending===0};},[approvals,scenes]);
 if(!visible)return null;
 if(!projectId)return <section className="bible-panel"><div className="heritage-callout">Save the film as a cloud project to unlock Production Review.</div></section>;
 return <section className="bible-panel premium-production">
  <div className="section-head"><div><div className="eyebrow">PREMIUM · PRODUCTION CONTROL</div><h2>From draft to approved master.</h2><p>Review cultural context, approve scenes, preserve versions and carry a Heritage Production Passport into the final film.</p></div></div>
  <div className="production-approval-banner"><div><div className="eyebrow">PRODUCTION CHECKPOINT</div><strong>{approvalSummary.ready?'✓ All scenes approved for final export':'Review before final export'}</strong><small>{approvalSummary.total?`${approvalSummary.approved}/${approvalSummary.total} scenes approved or locked.`:'Generate scenes to begin review.'}</small></div><span className={approvalSummary.ready?'approval-ready':'approval-pending'}>{approvalSummary.ready?'READY':'PENDING'}</span></div>
  <div className="panel-tabs">{[['review','Review'],['versions','Versions'],['passport','Passport']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='review'&&<><div className="card-inset"><div className="eyebrow">SCENE APPROVAL</div><p className="muted">Use <b>Review</b> while cultural or historical questions are open. Use <b>Approve</b> when the scene is cleared for final export. <b>Lock</b> records a deliberate final decision.</p>{scenes.length?scenes.map(s=>{const a=approvals.find(x=>x.scene_id===s.id);return <div className="member-row" key={s.id}><div><strong>{s.number}. {s.title}</strong><small>{a?.status||'draft'}</small></div><div className="inline-actions"><button onClick={()=>approve(s.id,'review')}>Review</button><button onClick={()=>approve(s.id,'approved')}>Approve</button><button onClick={()=>approve(s.id,'locked')}>Lock</button></div></div>}):<div className="heritage-callout">Generate scenes to start production review.</div>}</div><div className="card-inset"><div className="eyebrow">DIRECTOR NOTES</div><select aria-label="Attach note to scene" value={sceneId} onChange={e=>setSceneId(e.target.value)}><option value="">General project note</option>{scenes.map(s=><option value={s.id} key={s.id}>Scene {s.number} · {s.title}</option>)}</select><textarea aria-label="Add a note for the writer, researcher, editor or producer…" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a note for the writer, researcher, editor or producer…"/><button className="generate" onClick={addComment}>Add review note</button>{comments.slice(-6).reverse().map(c=><div className="comment-card" key={c.id}><small>{c.scene_id||'Project'} · {new Date(c.created_at).toLocaleString()}</small><p>{c.body}</p></div>)}</div></>}
  {tab==='versions'&&<div className="card-inset"><button className="generate" onClick={saveVersion}>Save production snapshot</button>{versions.map(v=><div className="member-row" key={v.id}><div><strong>v{v.version_number} · {v.label}</strong><small>{new Date(v.created_at).toLocaleString()}</small></div><button onClick={async()=>{try{const r=await apiFetch(`/api/projects/${projectId}/versions/${v.id}/restore`,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.message);setStatus('Version restored. Refresh the editor to load the restored state.')}catch(e){setStatus(e.message)}}}>Restore</button></div>)}</div>}
  {tab==='passport'&&<div className="passport-card"><div className="eyebrow">HERITAGE PRODUCTION PASSPORT</div><h3>{passport?.title||'Production passport'}</h3><p>{passport?.story||'No story captured yet.'}</p><div className="passport-grid"><div><small>ERA</small><strong>{passport?.era||'—'}</strong></div><div><small>LOCATION</small><strong>{passport?.location||'—'}</strong></div><div><small>SCENES</small><strong>{passport?.sceneCount||0}</strong></div><div><small>TYPE</small><strong>{passport?.storyType||'—'}</strong></div></div><h4>Sources</h4><p>{Array.isArray(passport?.sources)?passport.sources.join(' · '):passport?.sources||'No sources recorded.'}</p><h4>Research caution</h4><p>{passport?.uncertainties||'Separate documented evidence, oral tradition and creative reconstruction.'}</p><button onClick={()=>navigator.clipboard?.writeText(JSON.stringify(passport,null,2))}>Copy passport data</button></div>}
  {status&&<div className="heritage-callout">{status}</div>}
 </section>
}
