import React,{useMemo} from 'react';
function clean(value=''){return String(value||'').replace(/\s+/g,' ').trim()}
function tokens(value=''){return new Set(clean(value).toLowerCase().split(/[^a-z0-9À-ÿ]+/).filter(x=>x.length>3))}
function matchScore(a,b){const aa=tokens(a),bb=tokens(b);if(!aa.size||!bb.size)return 0;let n=0;aa.forEach(x=>{if(bb.has(x))n++});return n/Math.max(aa.size,1)}
export function ResearchStoryBridge({research,rootsFoundation,scenes=[]}){
 const evidence=useMemo(()=>[
  {key:'verified',label:'Documented facts',text:clean(research?.verifiedFacts),tone:'documented'},
  {key:'material',label:'Material culture',text:clean(research?.materialCulture),tone:'visual'},
  {key:'oral',label:'Oral / community memory',text:clean(research?.oralTraditions),tone:'oral'},
  {key:'uncertain',label:'Uncertainties',text:clean(research?.uncertainties),tone:'review'}
 ].filter(x=>x.text),[research]);
 const rows=useMemo(()=>evidence.map(e=>{const ranked=(scenes||[]).map(s=>({s,score:matchScore(`${s.title||''} ${s.prompt||''} ${s.visualAnchor||''} ${s.culturalContext||''}`,e.text)})).filter(x=>x.score>.05).sort((a,b)=>b.score-a.score).slice(0,3);return {...e,matches:ranked}}),[evidence,scenes]);
 const anchors=[rootsFoundation?.community,rootsFoundation?.country,rootsFoundation?.place,rootsFoundation?.language,rootsFoundation?.period].filter(Boolean);
 return <section className="card-inset research-story-bridge"><div className="section-head"><div><div className="eyebrow">RESEARCH → STORY → PRODUCTION</div><h3>Trace the roots behind the film</h3><p className="muted">See which research material is informing the story and scenes. Avirzo does not turn a source into “fact” automatically; evidence and review status travel with the project.</p></div></div><div className="bridge-meta"><span>{research?.evidenceLevel||'Evidence level not set'}</span><span>{research?.verificationStatus||'Verification not set'}</span>{research?.communityVoice&&<span>Steward: {research.communityVoice}</span>}{anchors.length>0&&<span>Roots: {anchors.join(' · ')}</span>}</div>{evidence.length===0?<div className="heritage-callout">Add documented facts, material culture or oral/community memory in Research to create traceable story context.</div>:<div className="bridge-list">{rows.map(e=><article className={`bridge-card bridge-${e.tone}`} key={e.key}><div className="bridge-card-head"><strong>{e.label}</strong><small>{e.tone==='review'?'Review boundary':'Context available'}</small></div><p>{e.text.slice(0,420)}{e.text.length>420?'…':''}</p>{e.matches.length>0?<div className="bridge-scenes"><small>Appears relevant to</small>{e.matches.map(({s})=><span key={s.id||s.number}>Scene {s.number||'?'} · {s.title||'Untitled scene'}</span>)}</div>:<div className="bridge-unmapped">Not yet visibly mapped to a scene.</div>}</article>)}</div>}{research?.sources?.length>0&&<div className="bridge-sources"><div className="eyebrow">SOURCE TRAIL</div>{research.sources.slice(0,6).map((x,i)=><a key={i} href={x.url} target="_blank" rel="noreferrer">{x.title||x.url}</a>)}</div>}</section>
}
